# Generated by Django 5.0.4 on 2024-04-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modal_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('chartin_counts', models.IntegerField()),
            ],
            options={
                'db_table': 'modal_chart',
            },
        ),
    ]
