# Generated by Django 5.0.4 on 2024-04-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(default='', max_length=100)),
                ('singer', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('week', models.IntegerField()),
                ('season', models.IntegerField()),
            ],
            options={
                'db_table': 'All_chart',
            },
        ),
        migrations.CreateModel(
            name='Monthly_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('temp', models.FloatField()),
            ],
            options={
                'db_table': 'Monthly_temp',
            },
        ),
        migrations.CreateModel(
            name='Spring_Modal_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('singer', models.CharField(default='', max_length=100)),
                ('years', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'spring_modal_chart',
            },
        ),
        migrations.CreateModel(
            name='Winter_Modal_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('singer', models.CharField(default='', max_length=100)),
                ('years', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'winter_modal_chart',
            },
        ),
        migrations.CreateModel(
            name='Yearly_weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('first_bloom', models.DateField()),
                ('first_snow', models.DateField()),
            ],
            options={
                'db_table': 'Yearly_weather',
            },
        ),
    ]
