# Generated by Django 4.2.11 on 2024-04-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spring_Modal_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('singer', models.CharField(default='', max_length=100)),
                ('years', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'spring_modal_chart',
            },
        ),
        migrations.CreateModel(
            name='Winter_Modal_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('singer', models.CharField(default='', max_length=100)),
                ('years', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'winter_modal_chart',
            },
        ),
        migrations.DeleteModel(
            name='Modal_chart',
        ),
    ]
