# Generated by Django 5.0.4 on 2024-04-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_all_chart_combine_season_chart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_chart',
            old_name='years',
            new_name='year',
        ),
    ]
